version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "localhost"
      MYSQL_DATABASE: "BankData"
      MYSQL_USER: "yassine"
      MYSQL_PASSWORD: ""
    volumes:
      - ./mysql-data:/var/lib/mysql
